{ ... }:
{
  wayland.windowManager.hyprland.settings = {
    # Hyprland 0.53+ syntax: match:class / match:title, boolean effects need " on"
    windowrule = [
      "float on, match:class ^(Viewnior)$"
      "float on, match:class ^(imv)$"
      "float on, match:class ^(mpv)$"
      "tile on, match:class ^(Aseprite)$"
      "pin on, match:class ^(rofi)$"
      "pin on, match:class ^(waypaper)$"
      "float on, match:title ^(Transmission)$"
      "float on, match:title ^(Volume Control)$"
      "float on, match:title ^(Firefox — Sharing Indicator)$"
      "move 0 0, match:title ^(Firefox — Sharing Indicator)$"
      "size 700 450, match:title ^(Volume Control)$"
      "move 40 55%, match:title ^(Volume Control)$"
      "float on, match:title ^(Picture-in-Picture)$"
      "opacity 1.0 1.0, match:title ^(Picture-in-Picture)$"
      "pin on, match:title ^(Picture-in-Picture)$"
      "opacity 1.0 1.0, match:title ^(.*imv.*)$"
      "opacity 1.0 1.0, match:title ^(.*mpv.*)$"
      "opacity 1.0 1.0, match:class ^(Aseprite)$"
      "opacity 1.0 1.0, match:class ^(Unity)$"
      "opacity 1.0 1.0, match:class ^(zen)$"
      "opacity 1.0 1.0, match:class ^(evince)$"
      "workspace 1, match:class ^(zen-beta)$"
      "workspace 3, match:class ^(evince)$"
      "workspace 4, match:class ^(Gimp-2.10)$"
      "workspace 4, match:class ^(Aseprite)$"
      "workspace 5, match:class ^(Audacious)$"
      "workspace 5, match:class ^(Spotify)$"
      "workspace 8, match:class ^(com.obsproject.Studio)$"
      "workspace 10, match:class ^(discord)$"
      "workspace 10, match:class ^(WebCord)$"
      "idle_inhibit focus, match:class ^(mpv)$"
      "idle_inhibit fullscreen, match:class ^(firefox)$"
      "float on, match:class ^(org.gnome.Calculator)$"
      "float on, match:class ^(waypaper)$"
      "float on, match:class ^(zenity)$"
      "size 850 500, match:class ^(zenity)$"
      "size 725 330, match:class ^(SoundWireServer)$"
      "float on, match:class ^(org.gnome.FileRoller)$"
      "float on, match:class ^(org.pulseaudio.pavucontrol)$"
      "float on, match:class ^(SoundWireServer)$"
      "float on, match:class ^(.sameboy-wrapped)$"
      "float on, match:class ^(file_progress)$"
      "float on, match:class ^(confirm)$"
      "float on, match:class ^(dialog)$"
      "float on, match:class ^(download)$"
      "float on, match:class ^(notification)$"
      "float on, match:class ^(error)$"
      "float on, match:class ^(confirmreset)$"
      "float on, match:title ^(Open File)$"
      "float on, match:title ^(File Upload)$"
      "float on, match:title ^(branchdialog)$"
      "float on, match:title ^(Confirm to replace files)$"
      "float on, match:title ^(File Operation Progress)$"
      "opacity 0.0, match:class ^(xwaylandvideobridge)$"
      "no_anim on, match:class ^(xwaylandvideobridge)$"
      "no_initial_focus on, match:class ^(xwaylandvideobridge)$"
      "max_size 1 1, match:class ^(xwaylandvideobridge)$"
      "no_blur on, match:class ^(xwaylandvideobridge)$"
      "border_size 0, match:float 0, match:workspace w[t1]"
      "rounding 0, match:float 0, match:workspace w[t1]"
      "border_size 0, match:float 0, match:workspace w[tg1]"
      "rounding 0, match:float 0, match:workspace w[tg1]"
      "border_size 0, match:float 0, match:workspace f[1]"
      "rounding 0, match:float 0, match:workspace f[1]"
      "opaque on, match:class ^()$, match:title ^()$"
      "no_shadow on, match:class ^()$, match:title ^()$"
      "no_blur on, match:class ^()$, match:title ^()$"
    ];

    # Layer rules: use match:namespace for 0.53+, boolean effects need explicit value
    layerrule = [
      "dimaround on, match:namespace vicinae"
      "dimaround on, match:namespace rofi"
      "dimaround on, match:namespace swaync-control-center"
    ];

    # Workspace-specific gap overrides (variables section)
    workspace = [
      "w[t1], gapsout:0, gapsin:0"
      "w[tg1], gapsout:0, gapsin:0"
      "f[1], gapsout:0, gapsin:0"
    ];
  };
}
